### ISSUE TITLE
[fluent-react] Use `message` attribute in <LocalizedElement>

### ISSUE THREAD

**Issue by Pike** [projectfluent/fluent.js#10]
Right now, fluent-react uses
```
<LocalizedElement id="hello-world">
```
Now, jsx looks like XML, and the `id` attribute has connotations about being unique in the source document, whereas this id is only unique in the MessageContext.

@stasm and I chatted about that, and we could use `message` instead:
```
<LocalizedElement message="hello-world">
```

**Comment by stasm** [comment]
We've been using `id` for over a year now and I think it works well. It's the identifier of the message which  `<Localized>` pulls from the `Localization` to localized the wrapped component. I haven't seen any confusion around it. Perhaps it's because in React the `id` doesn't have the same connotations as in HTML. (`key` does instead). Lastly, I appreciate the symmetry of the current API:

  - `fluent-dom`: `data-l10n-id`, `data-l10n-attrs`.
  - `fluent-react`: `<Localized id>`, `<Localized attrs>`.

The one exception is `data-l10n-args` in `fluent-dom` whose value is some serialized JSON. In `fluent-react` we're able to pass each arg as a separate `$`-prefixed prop to `<Localized>`.

I'm going to close this issue as _wontfix_. Thanks, @Pike!
