### ISSUE TITLE
How to create new custom functions as the built in functions...?

### ISSUE THREAD

**Issue by fernandogmar** [projectfluent/fluent.js#114]
Hi I am coming from here:
https://github.com/projectfluent/fluent/issues/78

the solution that @stasm pointed there woked fine only for strings:

```javascript
// Destructure the array of positional arguments to flag_value.
FLAG([flag_value]) {
    return flag_value? 'active' : 'inactive';
}
 ``` 

flag_value becomes something else (FluentNone) when it is `false` and becomes something else (FluentNumber) when it is for example `0`

Looking to: https://github.com/projectfluent/fluent.js/blob/dddb5db19bd5fc6a95a251cd7059cf26f187548d/fluent/src/builtins.js#L17

I could use  `value()` method to get the value... but that does half of the trick because FluentNone value is the same name/id of the variable.... :'(

```javascript
// Destructure the array of positional arguments to flag_value.
FLAG([flag_value]) {
    return value(flag_value)? 'active' : 'inactive';
}

function value(arg) {
  // StringExpression-typed options are parsed as regular strings by the
  // runtime parser and are not converted to a FluentType by the resolver.
  // They don't have the "value" property; they are the value.
  return typeof arg === 'string' ? arg : arg.value;
}
 ``` 

For some reason you are passing those objects to the function... I am completely out of context here... but just looking it from outside. Couldn't it be just enough for these `functions` to receive as input just the `real` value.... so it wouldn't be needed to know all those details when implementing these simple `functions`?

**Comment by stasm** [comment]
Thank you for taking time to write all of this down. I understand the problem better now.

The reason why we wrap everything in `FluentType` (which `FluentNone` and `FluentNumber` are subclasses of) is portability. Fluent is designed to be language-agnostic which allows us to have implementation is JS, Python, Rust, C# etc. `FluentType` is n abstraction layer for representing types that Fluent defines, regardless of whether the implementation language supports them. For instance, in Fluent we want to be able to tell `1` and `1.0` apart (because they might require different pluralizations: `1 apple`, `1.0 apples`). In JavaScript, both are represented as the same Number, which isn't enough for our use-case.

Everything passed to Fluent Functions will be an instance of `FluentType`. I'm sorry for not mentioning this earlier. Strings are an exception: for performance and memory reasons, in `fluent.js` we actually don't wrap them in `FluentString` (which doesn't exist) but instead piggy back on the fact that JavaScript Strings have a `toString` method. I just realized we can do the same thing with `valueOf` which means I was able to remove the `value` function you pasted above: https://github.com/projectfluent/fluent.js/commit/dea4f4c9961ef7de0784ddd25ba2b36251a74e44.

Looking at the code, `fluent.js` doesn't currently support passing booleans as arguments: https://github.com/projectfluent/fluent.js/blob/dddb5db19bd5fc6a95a251cd7059cf26f187548d/fluent/src/resolver.js#L335-L350

I'd suggest either converting your flag to a number on the caller's side, or, if you're up for a slightly more involved solution, creating a custom `FluentType` sublass: e.g. `FluentBool`. There's an early check in `ExternalArgument` which makes it possible to pass custom `FluentType` instances.

https://github.com/projectfluent/fluent.js/blob/dddb5db19bd5fc6a95a251cd7059cf26f187548d/fluent/src/resolver.js#L330-L333

Just make sure to implement a `toString` method on the subclass.

**Comment by fernandogmar** [comment]
hi @stasm,

thanks for all the details. Probably I am missing things, but I am curious, why the FluentBoolean is not already there:

https://github.com/projectfluent/fluent.js/blob/dddb5db19bd5fc6a95a251cd7059cf26f187548d/fluent/src/resolver.js#L335-L350

is a plan to supported as follow?:

since FluentBoolean could be almost as FluentNumber (even simpler):

```js
  switch (typeof arg) {
    case 'string':
      return arg;
    case 'number':
      return new FluentNumber(arg);
    case 'boolean':
      return new FluentBoolean(arg);
    case 'object':
      if (arg instanceof Date) {
        return new FluentDateTime(arg);
      }
    default:
      errors.push(
        new TypeError(`Unsupported external type: ${name}, ${typeof arg}`)
      );
      return new FluentNone(name);
  }
```
implemented as follow:
```js
export class FluentBoolean extends FluentType {
  constructor(value, opts) {
    super(!!value, opts);
  }

  toString(ctx) {
      return this.value.toString();
  }

  /**
   * Compare the object with another instance of a FluentType.
   *
   * @param   {MessageContext} ctx
   * @param   {FluentType}     other
   * @returns {bool}
   */
  match(ctx, other) {
    if (other instanceof FluentBoolean) {
      return this.value === other.value;
    }
    return false;
  }
}
```

**Comment by stasm** [comment]
Booleans are not currently supported by the Fluent Syntax so the JavaScript implementation doesn't include `FluentBoolean`. The best place to discuss adding booleans would be a new issue in https://github.com/projectfluent/fluent.

To support booleans, we'd need to add reserved keywords for `true` and `false` to the syntax. Otherwise, it won't be possible to create variants whose keys are booleans. `[true]` is parsed as a string right now and wouldn't triple-equals `match` a `FluentBoolean` from your example. There would also need to be rules for what to do if someone tries to interpolate a boolean into a string.

Back when we were discussing having booleans in the Syntax, we felt their usage would not be frequent and we speculated that most of the time, they can be replaced with numbers or strings (e.g. `status` which is `active` or `inactive` rather than a boolean called `active`). 

We also made sure it was possible to define custom Fluent subtypes by extending `FluentType` so that developers can add more types if they really need to.

**Comment by stasm** [comment]
Closing this because it isn't an actionable issue at this point.
