### ISSUE TITLE
Building improvements

### ISSUE THREAD

**Issue by brettz9** [projectfluent/fluent.js#119]
Howdy,

Just a very few quick questions based on a quick look at the repo (which I think would be more inviting for others digging in and getting their hands dirty with the code)...

1. Might you consider a cross-platform, wholly JavaScript-based build routine rather than Make files?
2. Why no public npm repo? (the 0.0.1 version ought to be enough to flag its alpha state)
3. How about a `module` field in `package.json` to indicate the Rollup entry file as well as `main` for any Node.js-based entry file usage?

Thanks!

**Comment by zbraniecki** [comment]
I'm not sure what you mean by "npm repo".

If you go to npmjs.com and search for fluent you'll find at the very top:

- https://www.npmjs.com/package/fluent
- https://www.npmjs.com/package/fluent-syntax
- https://www.npmjs.com/package/fluent-react

Are you looking for something else?

**Comment by brettz9** [comment]
Sorry I mean an npm package for fluent.js itself... The package.json [here](https://github.com/projectfluent/fluent.js/blob/master/package.json) is private and not available at https://www.npmjs.com/package/fluent-javascript

**Comment by brettz9** [comment]
And two small things:

1. It looks like http://projectfluent.org/fluent.js/fluent/ may need to be updated as its referring to http://projectfluent.io/ which is giving a 404
2. I see on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat) one argument missing from http://projectfluent.org/fluent/guide/functions.html#datetime : `hourCycle`

I think the above-referenced API documentation could also probably benefit from documenting the available built-in classes (`MessageArgument , `MessageNumberArgument`, and `MessageDateTimeArgument`) for use as part of partial arguments within `format` (if not the other exports, `mapContextSync` and `CachedIterable`) since looking through the API docs alone didn't make this apparent.

**Comment by stasm** [comment]
`fluent.js` is the name of this repository and it is not meant to be an npm package. It's marked as private on purpose. It only has the `package.json` so that we can specify common build dependencies for packages in the repo. These packages serve different purposes and it's up to developer to decide which ones they need. For instance, for integrating Fluent with React, you'll need `fluent`, `fluent-intl`polyfill`, `fluent-langneg` and `fluent-react`, but you can skip `fluent-dom` and `fluent-web`.

Each individual package already has the `module` field defined, for example the core `fluent` package:

https://github.com/projectfluent/fluent.js/blob/dea4f4c9961ef7de0784ddd25ba2b36251a74e44/fluent/package.json#L22

`make` has served us rather well so far and switching away from it would be a laborious task. I'd prefer to only do it if the benefits of switching are very significant.

May I ask you to open a new issue with all you reported in your last comment? All of these are valid bugs that we should fix. Let's keep this issue about the build and packaging.

Thanks!
