### ISSUE TITLE
Transition runtime parser to a TransformStream

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/fluent.js#18]
Once we get a good corpus of tests for the parser,  I'd like to try to replace the current runtime parser with a stream parser. :till says that it would be a perfect use case, and I can see a benefit of doing that.

This will not be ready for production until streams are widely available, but may be useful for our perf. critical implementations

https://github.com/whatwg/streams

**Comment by stasm** [comment]
The runtime parser currently uses regexes to speed up parsing. Switching to streams would effectively require a complete rewrite. It's not something I'd like to do at this point.

I'm closing this issue because it's not actionable right now. We might want to look into streams in the future, at which point we should re-open this or discuss anew.
