### ISSUE TITLE
FluentBundle.format() should accept a string identifier of a message or a path to an attribute

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent.js#208]
If #205 lands, we could change `MessageContext.format()` to accept an identifier of a message and format it directly to string. It would avoid the intermediate step of having to first `getMessage` the message from the context, which is a bit clunky and is an artifact of how the bindings retrieve translated attributes.

```js
// BEFORE
let message = ctx.getMessage("message-key");
let translation = ctx.format(msg, args);
```

```js
// AFTER
let translation = ctx.format("message-key", args);
```

For attributes, we could introduce the following syntax:

```js
// AFTER
let translation = ctx.format("message-key.attr-name", args);
```

**Comment by zbraniecki** [comment]
I'd like to suggest a transition period.

First, we would update `format` to take `id` or `id.attr` just like you did in Rust.

We would still preserve the `get_message` as semi-private way used by FluentDOM only for getting the whole shape all at once.

Then we can experiment with using the new `format` the way you suggested and analyze performance impact. I'm pretty skeptical about it because it just runs more code, but irrelevant, getting `format` to act the way we expect would be a big step forward and if we keep the `get_message` or not after that is less significant.

**Comment by stasm** [comment]
@zbraniecki Would that require moving the following logic into the `fluent` package?

https://github.com/projectfluent/fluent.js/blob/873b409385d73c9e8c181243226f5096241d8dbd/fluent-dom/src/localization.js#L208-L227

Or do you have something different in mind?

**Comment by zbraniecki** [comment]
yes, I believe so. It would return a formatted shape `Message {value, attributes}` in runtime.

**Comment by stasm** [comment]
I'd prefer to keep this code in `fluent-dom` and in `fluent-react`. As you know, I'm not sure it represents the right approach to formatting compound messages. I'd like to keep `fluent` agnostic and unopinionated. The bindings modules are better suited to host this code given that they are higher up in the ladder of abstraction and can be more opinionated.

Which leads me to conclude that during the transition period, `fluent` should have three methods:

  1. the current `getMessage(id: str) -> Message`
  1. the current `format(resolvable: Message|Attribute) -> string?`
  1. a new `formatString(id: str) -> string?`

Ideally, I'd prefer the method no. 3 to be called `format`, but I'm afraid of compatibility issues with `fluent-dom` and `fluent-react`. `fluent-react` currently lists `fluent >= 0.8.0` as its peer depenendency. If we change the behavior of `format`, I think we should first publish a new version of `fluent-react` (0.8.1) which doesn't allow `fluent` 0.9.0 as a peer dependency.

**Comment by zbraniecki** [comment]
So, the operations required to retrieve a formatted attributes change from:

1) call `formatMessage(id)`
2) iterate over `msg.attrs` and format each of them

to:

1) call `getMessageShape(id)`
2) iterate over `info.attrs` and
2.1) construct an `id.attrName` string that is passed to `format`
2.2) which then deconstructs this `id.attrName`, retrieves the message behind the `id` and retrieves it's `attrName` and formats it.

It seems to me like `2.1` and `2.2` become this quirky operations that don't find the model, but are there for some higher design principle, rather than operational efficiency.

The idea that for each attribute we have to construct an artificial identifier that instantly gets decomposed into a tuple, and that for each attribute the message has to be retrieved separately, seems to me like the wrong abstraction.

Since the model we're discussing in close to 100% cases the attributes in the FTL have the following characteristics:
1) They're allowed
2) They're necessary to localize the element
3) They're all necessary only together

and each scenario where either of the three is not true is an edge or error case, it seems to me like we should be optimizing the number of operations for the predominant scenario, not increasing.

I'm somewhere around -0.9 on the apache voting process scale. It seems to me like a pretty sharp increase in the number of operations to achieve the basic functionality needed for any compound message declarative localization API to work (in particular, DOM) compared to both current model and alternative proposals.

But I can imagine that due to heavy optimizations in JavaScript we may be able to switch to it without noticable performance cost in large scale tests like talos in Gecko. In that case, I would be sad we're doing that, and I would remain with my `votum separatum`, but wouldn't block here.

**Comment by stasm** [comment]
> It seems to me like 2.1 and 2.2 become this quirky operations that don't fit the model, but are there for some higher design principle, rather than operational efficiency.

One of the reasons behind this design is security. Similar to how the parser counts placeables in a pattern and to how the resolver keeps track of dirty patterns, this design makes the bundle be defensive about how many attributes might be defined on a message _before_ formatting them. A malicious translation from an unverified source could easily slow down `formatMessage` by an order or two orders of magnitude just by supplying more attributes than expected.

I think this risk is well mitigated for Mozilla where it's safe to assume that most apps will have their translations validated by `compare-locales`. The low-level API of `FluentBundle`, however, should be designed to be more robust fashion.

Ultimately, a malicious translation can be just plainly... wrong, which also constitutes an attack vector. Do you think building these guards into the `FluentBundle` API is worth the slight increase in code complexity?

> The idea that for each attribute we have to construct an artificial identifier that instantly gets decomposed into a tuple, and that for each attribute the message has to be retrieved separately inside the format function, seems to me like the wrong abstraction.

Thanks for bringing it up. I'm not too bothered about it, but it might be be a good idea to consider alternatives, like `format(id: str, attrname: str?, data: object?)`. It would make sense to me to try to unify this API across the implementations, but it's not absolutely necessary.

If we go the `formatMessage` route, I think the base `format` method should be renamed to `formatValue` for consistency. Which would be a good thing anyways since the signature would change, too.

**Comment by stasm** [comment]
Maybe an `iterateAttributes(messageId: str, max: number) -> Iterator over [name, formattedValue]` would make sense? It would only need to retrieve the message once, it would format the attribute right away, and it would provide a way to cap the number of format operations.

**Comment by stasm** [comment]
Admittedly, the capping logic could be performed on the side of the calling side, too. So maybe just `iterateAttributes(messageId: str)`.

**Comment by zbraniecki** [comment]
We tried the iterator with stas and got the following results: https://treeherder.mozilla.org/perf.html#/compare?originalProject=try&originalRevision=c6f68b69aaf2&newProject=try&newRevision=9d1627e52e78&framework=1

It's hard to judge a bit, I would lean toward the regressions being a fluke, but there may also be a small regression.

We decided to move forward with the iterator approach and if gecko will need it to be an array, we can fork that line of code in Gecko implementation.

**Comment by stasm** [comment]
Some more thoughts on this: the iterator approach gives us more flexibility, but it still doesn't allow hash-like look ups of attributes. I'd like to suggest a slightly different solution, very close to your original one, but with a modification which allows extensions of the API in the future without breaking changes.

I'd like to have two methods on `FluentBundle`:

1. `FluentBundle.format(path: str, args: object?): string?`, and
2. `FluentBundle.compound(id: str, args: object?): {value: string, attributes: Map {name: string, value: string}}?`.

`format` would take a message identifier (`foo`) or an attribute path (`foo.title`) and return the formatted translation as a string, or `null` if the translation doesn't exist.

`compound` would be used to build an object of `{value, attributes}`. The main use-case for this method are bindings, like `fluent-dom` and `fluent-react`. There, it's useful to ask `fluent` for all translations for a given element or component. Some bindings will prefer to just ask for all attributes and iterator over what they get (that's what `fluent-dom` currently does), while others ask for individual attributes based on what the component allows (that's what `fluent-react` does). To support both of these use-cases, `FluentBundle.compound` returns an object of `{value: string, attributes: Map}`. The `Map` interface provides both the iteration (`Map.entries()`) and lookup (`Map.get()`).

If, in the future, there's a concern about the performance of `FluentBundle.compound()` related to a high number of attributes which are formatted only to be thrown away by the bindings, we can swap the `Map` for a custom object which implements the same methods, but lazily. I.e. `attributes.get(name)` would only format the `name` attribute when it's called. For now, however, let's just use a regular eager `Map`.

@zbraniecki Let me know what you think. This is very close to your `formatMessage` proposal (or the same but with details which I missed in it 😀 ) and will support the `fluent-dom` and the Gecko use-cases very well. If you agree, I'd like to move ahead with the implementation.

**Comment by zbraniecki** [comment]
I agree! That looks like the right way forward! Thanks for taking feedback Stas!

I'm not sure if I like the name, `format` is a verb, while `compound` is a noun. That makes the two methods sound differently when used in a sentence.

I think I prefer to either use `formatMessage` or `formatCompoundMessage` for that, but that's, unsurprisingly, name bikeshedding, so low prior. :)

**Comment by stasm** [comment]
Thanks.

`compound` [is a verb](https://www.merriam-webster.com/dictionary/compound), too, but I'll be happy to ask a native speaker for input. I prefer these shorter names, but we could also go with `formatValue` and `formatMessage`.

**Comment by stasm** [comment]
Regardless of the how we call these methods, we also need to work on the implementation. I'd like to ship this change in the next version of `fluent`. @unclenachoduh I know you mentioned you'd be interested in giving this a try. Let me know how I can help :)

**Comment by stasm** [comment]
We're going to the go with the `formatPattern` proposal in #380.
