### ISSUE TITLE
Using \u000a breaks getMessage

### ISSUE THREAD

**Issue by danilobuerger** [projectfluent/fluent.js#361]
Setup bundle like:
```
const test = new FluentBundle("de-DE");
test.addMessages(`msg = {"\u000a"}`);
```

Calling `test.getMessage("msg")` will return `undefined`.

**Comment by stasm** [comment]
Thanks for reporting this. I've tried to parse `msg = {"\u000a"}` and everything looks OK.

I wonder if this might be an escaping issue on the side of the JS code? Fluent uses `\` as the escape character, same as JavaScript. If you're adding messages from within JS code, you need to escape the backslash twice: once for the JS parser, and the second time for Fluent:

```js
const test = new FluentBundle("de-DE");
test.addMessages(`msg = {"\\u000a"}`);
```

This works fine.

If you don't double-escape the `\u000a`, JS converts it to a line feed character:

```js
const test = new FluentBundle("de-DE");
test.addMessages(`msg = {"
"}`);
```

This results in a syntax error on Fluent's side because string literals must be written on a single line.

**Comment by danilobuerger** [comment]
You are absolutely right. Sorry for the noise and thanks! Works with `\\u000a` inside JS and `\u000a` from non-JS code.

Maybe this could be added to https://projectfluent.org/fluent/guide/special.html so that other users don't fall into the same trap.

My use case: I keep the ftl "files" as javascript files to include them easily in a react native project. Without compile time tooling, this is the easiest (?) way to handle it. So now I have to watch out that everything is double escaped (JS and Fluent).

**Comment by stasm** [comment]
Good idea. I added a note in https://github.com/projectfluent/fluent/commit/1e716666b90a58c90d4b4e366919685f75fdf9fb and deployed it live. Happy to take a PR if the wording could be improved :) I just wanted to put something online to not forget about it later. Thanks again!

**Comment by danilobuerger** [comment]
Perfectly clear, thanks for adding it!
