### ISSUE TITLE
@fluent/syntax: Variant values with `[]` don't roundtrip through the parser/serializer

### ISSUE THREAD

**Issue by Pike** [projectfluent/fluent.js#512]
The following Fluent snippet doesn't round-trip right:

```properties
shared-photos =
    { $userName } { $photoCount ->
        [one][x]added a new photo { $item ->
                [bucket] to the bucket
               *[folder] to the folder
            }
       *[other] added { $photoCount } new photos
    }
```

The result is

```properties
shared-photos =
    { $userName } { $photoCount ->
        [one]
            [x]added a new photo { $item ->
                [bucket] to the bucket
               *[folder] to the folder
            }
       *[other] added { $photoCount } new photos
    }
```
Filing here, but it affects all of `js`, `python`, and `kotlin`.

**Comment by Pike** [comment]
This code here

https://github.com/projectfluent/fluent.js/blob/f41d910dd3bbf13ac057026060a0666426796870/fluent-syntax/src/serializer.ts#L146-L148

doesn't take into account that `block_text` starts with `indented_char`,

https://github.com/projectfluent/fluent/blob/7282b865958ea0602ddc6b3d583ab7477abb49e7/spec/fluent.ebnf#L110

aka,  `- "[" - "*" - "."`.

Easy to fix. @stasm, I'm not sure where to test this, though. Should we go as far as have tests in the spec to ensure those are all parse errors?
And then,  yes, serializer tests, too.

**Comment by Michael-F-Bryan** [comment]
As far as I can tell, the issue is that `[one][x]` is serialized to `[one]\n[x]` (i.e the literal `[x]` starts on a newline, maybe with some indents)... Is it guaranteed that a serializer should preserve all whitespace? I thought the whitespace before a variant's first pattern element wasn't significant.

When I was implementing projectfluent/fluent-rs#184 I noticed that test inputs were constructed so things round-trip exactly, but just thought that was to make testing easier and not because it's required by the spec.

**Comment by Pike** [comment]
Usually white-space around  syntax elements is not significant, but in this case, newlines are. That's in the grammar snippet I  linked to.

Generally speaking, handling white-space with proper round-tripping is a pro for tooling applications. It's easier that way to not have different tools battle over how to serialize strings. There are tricks to lessen the impact (compare ASTs when deciding to write messages, for example), but generally, full round-trip is good for tooling.

Not that I know of  an implementations that does that.
