### ISSUE TITLE
Selector for custom function output

### ISSUE THREAD

**Issue by kueda** [projectfluent/fluent.js#630]
I'm trying to define a custom function to detect whether a variable begins with a vowel or a consonant:

```javascript
VOWORCON: ( [txt] ) => (
  "aeiou".indexOf( txt[0].toLowerCase( ) ) >= 0
    ? "vow"
    : "con"
)
```

If I define a message like

```fluent
voworcon-test = Vowel or consonant: { VOWORCON( $test ) }
```

and call it with `t( "voworcon-test", { test: "albatross" } )`, I get `Vowel or consonant: vow` as I'd expect.

However, if I define a message with a selector like

```fluent
voworcon-test =
    This is
    { VOWORCON( $test ) ->
        [vow] an { $test }
       *[con] a { $test }
    }
```

and call it with `t( "voworcon-test", { test: "albatross" } )`, I get `voworcon-test` instead of `This is an albatross`.

Is this expected behavior? I'm using [i18next-fluent](https://github.com/i18next/i18next-fluent) so maybe this is a bug there... or maybe I don't understand something about how custom functions and selectors are supposed to work. FWIW I did not see a test for this specific case in https://github.com/projectfluent/fluent.js/blob/main/fluent-bundle/test/select_expressions_test.js or https://github.com/projectfluent/fluent.js/blob/main/fluent-bundle/test/functions_test.js

**Comment by eemeli** [comment]
You're right, this was not well enough covered by tests. So I added one in fee2242 to verify that it works as expected in our code. This might indeed be a bug in another package.

On a separate note, the English rules for a/an are primarily dependent on the sound and secondarily on customs, rather than the letter starting the word, and just checking against `aeiou` will often not work. A while back in a somewhat different context, I ended up putting together [this regexp](https://github.com/messageformat/messageformat/blob/d188fc449508cb2267f45a90361e15bb296a3ce2/packages/mf2-messageformat/src/mf2-features.test.ts#L294-L295), which is still wrong, but perhaps a little bit _less_ wrong than your current check.

**Comment by kueda** [comment]
Thank you, @eemeli! I've been tinkering with this today and came to the same conclusion you did about this package behaving as expected, so I'll close this. Thank you for adding that test. And good point about "a/n" and vowel-ish sounds in English. I may try your regex, though we'll see how it performs with all the other languages.
