### ISSUE TITLE
fluent-syntax: Consider using parser combinators

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent.js#68]
Given our EBNF it might make sense to rewrite the full AST parser as an LL(1) parser combinator.

I found the following two resources very helpful in understanding the principle:

http://www.garshol.priv.no/download/text/bnf.html
https://medium.com/@chetcorcos/introduction-to-parsers-644d1b5d7f3d

**Comment by zbraniecki** [comment]
I would like to see that. When I was rewriting the parser the last time I toyed with this approach and ended up rejecting for the following reasons:

* The syntax was in flux, and I didn't want to introduce the new parsing paradigm at the same time as I was trying to keep the parser in sync with a quickly changing grammar.
* I was working in rust, and there wasn't that much ready to use tooling for LL parser combinators (and my rust skills weren't very high)
* I was focused on exploring the streamable parser approach
* I was worried about our flexibility to recover from errors.

But none of those reasons are valid reasons now not to try. I'd love to see us automating as much as possible of the parser generation, and since fluent-syntax is not performance bound, I'm not worried about that aspect.

**Comment by stasm** [comment]
We now have the reference parser implemented using parser combinators at https://github.com/projectfluent/fluent/tree/master/syntax. This approach is very precise, but is currently slower and doesn't produce as good error messages as the current tooling parser. Closing.
