### ISSUE TITLE
[fluent-react] not pulling from '/compat' build of fluent-react causes console warnings

### ISSUE THREAD

**Issue by hkasemir** [projectfluent/fluent.js#91]
version 0.4.1 - using latest Firefox and Chrome browsers.

If I pull all components from `fluent-react`, I get console warnings:

`Warning: Failed context type: The l10n context field must be an instance of ReactLocalization.`

the warning provides a stack trace to a component using fluent-react components, if I change the import for fluent-react in that component to pull from fluent-react/compat, the error goes away.

It's not entirely clear what needs to happen to allow for imports from the base library.

**Comment by stasm** [comment]
I don't know how to reproduce this. In #97 I changed all examples to import from ES2015+ `fluent` modules rather than their `compat` counterparts. I'm not seeing any warnings.

This might be related to the build setup that you're using. Is there any chance you'd be able to create a minimized testcase for this?

The goal of the `compat` builds is to provide ES5 packages ready to be integrated into build pipelines which don't transpile dependencies. For instance, for production builds `create-react-app` expects all dependencies to already be transpiled to ES5. It runs UglifyJS on them which breaks on ES2015+ code.

Depending on how you build your project and how you handle dependencies, importing from `fluent-react/compat` might be a more bullet-proof approach. Not to say that we shouldn't get to the bottom of those warnings, of course.

**Comment by stasm** [comment]
@hkasemir and I talked about this yesterday and we found the reason of the warning.

Both `<LocalizationProvider>` and `<Localized>` use `ReactLocalization`. `<LocalizationProvider>` instantiates it and exposes as React's context:

https://github.com/projectfluent/fluent.js/blob/beabadab3e1fcb33a7ffbf736dd237fc63d2833f/fluent-react/src/provider.js#L37

`<Localized>` checks the type of exposed context objects:

https://github.com/projectfluent/fluent.js/blob/beabadab3e1fcb33a7ffbf736dd237fc63d2833f/fluent-react/src/localized.js#L128-L130

If someone imports `LocalizationProvider` from `fluent-react` and `Localized` from `fluent-react/compat` (or the other way around), the check fails because technically, those are two different `ReactLocalization` classes, from two different modules.

The fix is to always import from the same module:

```js
import { LocalizationProvider } from 'fluent-react';
import { Localized } from 'fluent-react';
```

Or:

```js
import { LocalizationProvider } from 'fluent-react/compat';
import { Localized } from 'fluent-react/compat';
```

Also, keep in mind that as of December 2017, UglifyJS used by `create-react-app` still doesn't parse ES2015+ code (see https://github.com/facebookincubator/create-react-app/issues/496, https://github.com/facebookincubator/create-react-app/issues/568, https://github.com/facebookincubator/create-react-app/issues/1125), so the safest way to use any `fluent-*` module is via the `compat` builds.
